# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container: node:12.16.2-buster-slim

    services:
      redis:
        image: redis

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies
      # in the `package.json` file
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          HOST: "localhost"
          BROADCAST_PORT: 9000
          LISTENER_PORT: 9001
          LISTENER_CHANNEL: "test_channel"
          REDIS_URL: "redis://redis:6379"
